### PR TITLE
Update NuGet-4.6-rtm.md

### PR DESCRIPTION
**Pull request by keunyop**
some grammar fix

### CODE REVIEW

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by v-elcou** [comment]
Hello, @keunyop:
Thank you for your contribution! We are processing your suggestions and we will update you shortly.
 
Kind regards,
Microsoft DOCS International Team

**Comment by v-cchen** [comment]
Hello, @keunyop 

Thank you for your contribution! Your suggestions have been partially accepted. We will merge your PR, but we will commit a new PR to revert the declined suggestions. The accepted suggestions will be used into the next article update. Below you will find comments on suggestions: 

Line:49 use original translation

Line:59
Current version: 비호환 패키지를 설치할 때 이해하기 어려운 오류 개선 - [#4555](https://github.com/NuGet/Home/issues/4555)
Requested change: 호환되지 않는 패키지를 설치할 때 이해하기 어려운 오류 개선 - [#4555](https://github.com/NuGet/Home/issues/4555)

Kind regards, 
Microsoft DOCS Global Experience Team

**Comment by LisandroSu** [comment]
@keunyop :

Thank you for your feedback and suggestion!

We agree with your suggestions, and we will include them into the next article update release.

Thank you for your time and support.
Microsoft C&E Localization Team

**Pull request merged**
